Repository LemonAppDev/konsist, pull requests merged in 2023-10, with the labels that each got.

#666 Update Docs
  lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/KoArchitectureAssertion.kt
Labels: documentation

#668 KON-521 Rename `KoReturnTypeProvider` To `KoReturnProvider`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koreturntype/KoReturnProviderExtTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoReturnProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturnprovider/extension-function-not-return-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturnprovider/extension-function-return-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturnprovider/function-not-return-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturnprovider/function-return-import-alias.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturnprovider/function-return-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturnprovider/function-with-block-body-and-declared-type-has-string-return-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturnprovider/function-with-block-body-and-declared-type-has-unit-return-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturnprovider/function-with-block-body-and-without-declared-type-has-unit-return-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturnprovider/function-with-expression-body-and-declared-type-has-string-return-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturnprovider/function-with-expression-body-and-declared-type-has-unit-return-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturnprovider/function-with-expression-body-and-without-declared-type-has-string-return-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturnprovider/function-with-expression-body-and-without-declared-type-has-unit-return-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/assertempty/AssertEmptyOnProviderListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/assertempty/AssertEmptyOnProviderSequenceTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoFunctionDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoReturnProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/provider/KoReturnProviderExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoReturnProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFunctionDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoReturnProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoReturnProviderListExtTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/provider/KoReturnProviderExtTest.kt
Labels: breaking-api-change, improvement

#670 KON-526 Rename `suppressName` To `testName` And Update Error Logic
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/assertempty/AssertEmptyOnDeclarationListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/assertempty/AssertEmptyOnDeclarationSequenceTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/assertempty/SuppressAssertEmptyOnDeclarationListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/assertempty/SuppressAssertEmptyOnSequenceListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/assertempty/snippet/declaration-assert-test-method-name-derived-from-junit-method-name.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/assertempty/snippet/declaration-assert-test-method-name-derived-from-test-name-parameter.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/assertnull/AssertNullOnSingleDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/assertnull/SuppressAssertNullOnSingleDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/assertnull/snippet/declaration-assert-test-method-name-derived-from-junit-method-name.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/assertnull/snippet/declaration-assert-test-method-name-derived-from-test-name-parameter.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/AssertTrueOnDeclarationListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/AssertTrueOnDeclarationSequenceTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/AssertTrueOnSingleDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/SuppressAssertTrueOnDeclarationListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/SuppressAssertTrueOnDeclarationSequenceTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/SuppressAssertTrueOnSingleDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/snippet/declaration-assert-test-method-name-derived-from-junit-method-name.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/snippet/declaration-assert-test-method-name-derived-from-test-name-parameter.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/snippet/file-declaration-assert-test-method-name-derived-from-junit-method-name.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/snippet/file-declaration-assert-test-method-name-derived-from-test-name-parameter.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/assertempty/AssertEmptyOnProviderListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/assertempty/AssertEmptyOnProviderSequenceTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/assertempty/SuppressAssertEmptyOnProviderListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/assertempty/SuppressAssertEmptyOnProviderSequenceTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/assertempty/snippet/provider-assert-test-method-name-derived-from-junit-method-name.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/assertempty/snippet/provider-assert-test-method-name-derived-from-test-name-parameter.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/assertnull/AssertNullOnSingleProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/assertnull/SuppressAssertNullOnSingleProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/assertnull/snippet/provider-assert-test-method-name-derived-from-junit-method-name.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/assertnull/snippet/provider-assert-test-method-name-derived-from-test-name-parameter.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/asserttrue/AssertTrueOnProviderListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/asserttrue/AssertTrueOnProviderSequenceTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/asserttrue/AssertTrueOnSingleProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/asserttrue/SuppressAssertTrueOnProviderListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/asserttrue/SuppressAssertTrueOnProviderSequenceTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/asserttrue/SuppressAssertTrueOnSingleProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/asserttrue/snippet/provider-assert-test-method-name-derived-from-junit-method-name.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/asserttrue/snippet/provider-assert-test-method-name-derived-from-test-name-parameter.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/verify/KoDeclarationAndProviderAssert.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt
Labels: bug-fix, improvement

#671 KON-529 Throw `KoAssertionFailedException` In `assertArchitecture`
  lib/build.gradle.kts
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture2/Architecture2Test.kt
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture2/project/domain/sample/DomainSecondClass.kt
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture2/project/presentation/sample/PresentationSecondClass.kt
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture2/project/presentation/sample/PresentationThirdClass.kt
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture4/Architecture4Test.kt
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture5/Architecture5Test.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/DependencyRulesCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoArchitectureAssert.kt
Labels: breaking-api-change

#639 KON-282 Improve `update-snippet` Script
  lib/src/snippet/kotlin/com/lemonappdev/konsist/android-snippets.md
  lib/src/snippet/kotlin/com/lemonappdev/konsist/architecture-snippets.md
  lib/src/snippet/kotlin/com/lemonappdev/konsist/clean-architecture-snippets.md
  lib/src/snippet/kotlin/com/lemonappdev/konsist/general-snippets.md
  lib/src/snippet/kotlin/com/lemonappdev/konsist/kotest-snippets.md
  lib/src/snippet/kotlin/com/lemonappdev/konsist/kotlin-serialization-snippets.md
  lib/src/snippet/kotlin/com/lemonappdev/konsist/library-snippets.md
  lib/src/snippet/kotlin/com/lemonappdev/konsist/spring-snippets.md
  lib/src/snippet/kotlin/com/lemonappdev/konsist/test-snippets.md
  scripts/update_snippets.py
Labels: documentation

#680 KON-532 `hasBlockBody` In KoBodyProvider Returns True When Declaration Has No Body
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoBodyProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkobodyprovider/function-has-no-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kogetter/KoGetterDeclarationForKoBodyProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kogetter/snippet/forkobodyprovider/getter-has-no-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kosetter/KoSetterDeclarationForKoBodyProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kosetter/snippet/forkobodyprovider/setter-has-no-body.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoBodyProviderCore.kt
Labels: bug-fix

#681 KON-530 Rename `KoImplementationProvider` To `KoInitializerProvider`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoImplementationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoInitializerProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoimplementationprovider/function-inside-interface-has-implementation-in-block-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoimplementationprovider/function-inside-interface-has-implementation-in-expression-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoinitializerprovider/function-has-implementation-in-block-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoinitializerprovider/function-has-implementation-in-expression-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoinitializerprovider/function-inside-interface-has-no-implementation.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoinitializerprovider/function-inside-interface-is-not-initialized.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoinitializerprovider/function-is-initialized-in-block-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoinitializerprovider/function-is-initialized-in-expression-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kogetter/KoGetterDeclarationForKoInitializerProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kogetter/snippet/forkoinitializerprovider/getter-is-initialized-in-block-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kogetter/snippet/forkoinitializerprovider/getter-is-initialized-in-expression-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kogetter/snippet/forkoinitializerprovider/getter-is-not-initialized.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationForKoImplementationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationForKoInitializerProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoimplementationprovider/property-inside-interface-has-implementation-in-expression-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoinitializerprovider/property-has-implementation-in-getter-block-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoinitializerprovider/property-has-implementation-in-getter-expression-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoinitializerprovider/property-inside-interface-has-no-implementation.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoinitializerprovider/property-inside-interface-is-not-initialized.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoinitializerprovider/property-is-initialized-in-default-getter.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoinitializerprovider/property-is-initialized-in-getter-block-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoinitializerprovider/property-is-initialized-in-getter-expression-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kosetter/KoSetterDeclarationForKoInitializerProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kosetter/snippet/forkoinitializerprovider/setter-is-initialized-in-block-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kosetter/snippet/forkoinitializerprovider/setter-is-initialized-in-expression-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kosetter/snippet/forkoinitializerprovider/setter-is-not-initialized.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoFunctionDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoGetterDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoPropertyDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoSetterDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoImplementationProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoInitializerProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoImplementationProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoInitializerProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFunctionDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoGetterDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPropertyDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoSetterDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoImplementationProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoInitializerProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoImplementationProviderListExtTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoInitializerProviderListExtTest.kt
Labels: breaking-api-change

#679 KON-176 `DeveloperReadMe` Update Naming Conventions Section
  DeveloperReadme.md
Labels: documentation

#682 KON-199 Add `value` To KoPropertyDeclaration
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/KoAnnotationDeclarationForKoArgumentProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koargument/KoArgumentDeclarationForKoValueProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/KoEnumConstantDeclarationForKoArgumentProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationForKoValueProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkovalueprovider/property-has-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkovalueprovider/property-inside-interface-has-no-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkovalueprovider/property-with-delegation-has-no-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkovalueprovider/property-with-getter-and-setter-has-no-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkovalueprovider/property-with-getter-and-setter-has-value.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoPropertyDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoValueProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoValueProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoArgumentDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPropertyDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoValueProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoValueProviderListExtTest.kt
Labels: breaking-api-change

#687 KON-195 Rename Python Scripts
  .github/workflows/check-starter-projects.yml
  scripts/get_artifact_path.py
  scripts/replace_konsist_version/add_maven_local_repository_to_config_file.py
  scripts/replace_konsist_version/replace_konsist_version_gradle_groovy.py
Labels: CI

#696 Add Article
  README.md
Labels: documentation

#703 Upd Konsist Artifact Description
  buildSrc/src/main/kotlin/local.publish.gradle.kts
Labels: documentation

#705 Add Article
  README.md
Labels: documentation

#704 Fix Typo
  samples/starter-projects/konsist-starter-spring-gradle-kotlin-kotest/src/konsistTest/kotlin/com/sample/SampleKonsistTest.kt
Labels: improvement

#708 Add Article "Konsist and Conquer: Embracing the World of Dynamic Testing"
  README.md
Labels: documentation

#712 KON-538 Add `testName` To `assertArchitecture`
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/optionalparameters/OptionalParametersTest.kt
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/optionalparameters/project/domain/DomainFirstClass.kt
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/optionalparameters/project/domain/sample/DomainSecondClass.kt
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/optionalparameters/project/presentation/PresentationFirstClass.kt
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/optionalparameters/project/presentation/sample/PresentationSecondClass.kt
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/optionalparameters/project/presentation/sample/PresentationThirdClass.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/KoArchitectureAssertion.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/KoArchitectureAssertionCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/CommonAssert.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoArchitectureAssert.kt
Labels: improvement

#719 KON-553: Allow `null` values in representsType()
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/KoAnnotationDeclarationForKoRepresentsTypeProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoRepresentsTypeProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoRepresentsTypeProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoRepresentsTypeProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/KoParameterDeclarationForKoRepresentsTypeProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoRepresentsTypeProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/provider/KoRepresentsTypeProviderExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoRepresentsTypeProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParameterDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoRepresentsTypeProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoRepresentsTypeProviderListExtTest.kt
Labels: improvement

#733 Upd docs
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/provider/KoExternalParentProviderExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoExternalParentProvider.kt
Labels: documentation

#720 Replace REGEX to allow using .. as wildcard again
  lib/src/main/kotlin/com/lemonappdev/konsist/core/util/LocationUtil.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/architecture/LayerTest.kt
Labels: improvement

#734 Upd docs
  lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/Layer.kt
Labels: documentation
