Repository LemonAppDev/konsist, pull requests merged in 2023-11, with the labels that each got.

#740 Add Snippet
  lib/src/snippet/kotlin/com/lemonappdev/konsist/SpringSnippets.kt
Labels: documentation

#749 Improve Gradle build performance
  gradle.properties
Labels: CI

#724 KON-562: Improve snippet CI verification
  .github/workflows/check-kttxt-snippets.yml
  scripts/check_kttxt_snippets.py
Labels: CI

#754 KON-571 Fix `isKotlinType` Property Where Generic Types Where Treated as kotlin Collections
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/KoTypeDeclarationForKoKotlinTypeProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoKotlinTypeProviderCore.kt
Labels: bug-fix

#753 KON-570 Add `KoSourceAndAliasTypeProviderCore.baseSourceType`
  .github/workflows/check.yml
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/KoTypeDeclarationForKoKotlinTypeProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/KoTypeDeclarationForKoSourceAndAliasTypeProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkokotlintypeprovider/sample-collection-with-two-type-arguments-and-one-is-kotlin-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkosourceandaliastypeprovider/generic-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkosourceandaliastypeprovider/generic-with-nullable-type-argument.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkosourceandaliastypeprovider/import-alias.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkosourceandaliastypeprovider/nullable-generic-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkosourceandaliastypeprovider/nullable-generic-with-nullable-type-argument.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkosourceandaliastypeprovider/nullable-import-alias.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkosourceandaliastypeprovider/nullable-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkosourceandaliastypeprovider/simple-list-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkosourceandaliastypeprovider/simple-nullable-list-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkosourceandaliastypeprovider/simple-nullable-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkosourceandaliastypeprovider/type.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoSourceAndAliasTypeProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoSourceAndAliasTypeProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoKotlinTypeProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoSourceAndAliasTypeProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoSourceAndAliasTypeProviderListExtTest.kt
Labels: improvement

#756 KON-572 Fix for `sourcetype` stripping `?`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/KoTypeDeclarationForKoFullyQualifiedNameProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/KoTypeDeclarationForKoSourceAndAliasTypeProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/list-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/nullable-list-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/nullable-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/type.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoFullyQualifiedNameProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoSourceAndAliasTypeProviderCore.kt
Labels: bug-fix

#758 KON-570 Rename `baseSourceType` To `bareSourcetype`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/KoTypeDeclarationForKoSourceAndAliasTypeProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoSourceAndAliasTypeProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoSourceAndAliasTypeProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoFullyQualifiedNameProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoKotlinTypeProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoSourceAndAliasTypeProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoSourceAndAliasTypeProviderListExtTest.kt
Labels: improvement

#771 Update README.md
  README.md
Labels: documentation

#715 KON-366 Change Return Type Of `containingDeclaration`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoContainingDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koconstructor/KoConstructorDeclarationForKoContainingDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoContainingDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kogetter/KoGetterDeclarationForKoContainingDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koinitblock/KoInitBlockDeclarationForKoContainingDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoContainingDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoContainingDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationForKoContainingDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kosetter/KoSetterDeclarationForKoContainingDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypealias/KoTypeAliasDeclarationForKoContainingDeclarationProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoContainingDeclarationProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoContainingDeclarationProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/cache/KoDeclarationCache.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoAnnotationDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoArgumentDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoClassDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoEnumConstantDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFunctionDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoGetterDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoImportDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoInitBlockDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoInterfaceDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoObjectDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPackageDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParameterDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentClassDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentInterfaceDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPrimaryConstructorDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPropertyDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoSecondaryConstructorDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoSetterDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoTypeAliasDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoVariableDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/ext/KoBaseProviderExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoAnnotationProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoContainingDeclarationProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoEnumConstantProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoGetterProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoImportProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoInitBlockProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoNullableTypeProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoParametersProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoPrimaryConstructorProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoReceiverTypeProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoReturnProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoSecondaryConstructorsProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoSetterProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoTypeAliasProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/util/KoDeclarationProviderCoreUtil.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/util/KoLocalDeclarationProviderCoreUtil.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/util/ReceiverUtil.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoContainingDeclarationProviderListExtTest.kt
Labels: breaking-api-change

#766 Add Spring Snippet
  lib/src/snippet/kotlin/com/lemonappdev/konsist/KotlinSerializationSnippets.kt
  lib/src/snippet/kotlin/com/lemonappdev/konsist/SpringSnippets.kt
Labels: documentation
