Repository LemonAppDev/konsist, pull requests merged in 2023-09, with the labels that each got.

#424 Add Clean Architecture Check to README.md
  README.md
Labels: documentation

#430 KON-373 Update KoFullyQualifiedNameProvider.fullyQualifiedName Implementation To Not Return Empty String
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/KoAnnotationDeclarationForKoFullyQualifiedNameProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/KoParentDeclarationForKoFullyQualifiedNameProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/parent-fully-qualified-name-without-import.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/KoTypeDeclarationForKoFullyQualifiedNameProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoAnnotationDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPackageDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoTypeDeclarationCore.kt
Labels: major-api-change

#431 KON-377 Remove Duplication In `localDeclarations` Definition
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoEnumConstantDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFunctionDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoInitBlockDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/util/KoLocalDeclarationProviderCoreUtil.kt
Labels: path-api-change

#442 KON-381 Add Lambda As Last Argument Of `print` Function
  lib/src/main/kotlin/com/lemonappdev/konsist/api/container/KoScope.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoBaseProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoTextProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/container/KoScopeCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoTextProviderCore.kt
Labels: path-api-change

#443 KON-382 Change Default Behaviour Of `print`
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoBaseProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoBaseProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoTextProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoBaseProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoTextProviderCore.kt
Labels: path-api-change

#446 KON-393 Change Return Type Of `print` From Unit To Declaration Instance
  lib/src/main/kotlin/com/lemonappdev/konsist/api/container/KoScope.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoBaseProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/provider/KoBaseProviderExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoBaseProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/container/KoScopeCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoBaseProviderCore.kt
Labels: path-api-change

#447 KON-388 Add `countX { ... }` methods
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoConstructorProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoEnumConstantProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoInitBlockProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoParentProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoSecondaryConstructorsProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/forkomodifier/KoClassDeclarationForKoModifierProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/snippet/forkoconstructorsprovider/class-has-primary-and-secondary-constructors.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/snippet/forkoinitblockprovider/class-with-two-init-blocks.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/snippet/forkosecondaryconstructorsprovider/class-has-secondary-constructor.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koconstructor/KoConstructorDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koconstructor/KoConstructorDeclarationForKoParametersProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koconstructor/forkomodifier/KoConstructorDeclarationForKoModifierProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/KoEnumConstantDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/KoFileDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/KoFileDeclarationForKoImportProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/KoFileDeclarationForKoTypeAliasProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoParametersProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/forkomodifier/KoFunctionDeclarationForKoModifierProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoParentProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/forkomodifier/KoInterfaceDeclarationForKoModifierProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoInitBlockProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoParentProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/forkomodifier/KoObjectDeclarationForKoModifierProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/snippet/forkoinitblockprovider/object-with-two-init-blocks.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/KoParameterDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/forkomodifier/KoParameterDeclarationForKoModifierProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/forkomodifier/KoPropertyDeclarationForKoModifierProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypealias/KoTypeAliasDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypealias/forkomodifier/KoTypeAliasDeclarationForKoModifierProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoAnnotationProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoConstructorProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoEnumConstantProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoImportProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoInitBlockProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoParametersProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoParentProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoSecondaryConstructorsProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoTypeAliasProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/modifier/KoModifierProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFunctionDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoAnnotationProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoConstructorProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoEnumConstantProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoImportProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoInitBlockProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoParametersProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoParentProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoSecondaryConstructorsProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoTypeAliasProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoModifierProviderCore.kt
Labels: minor-api-change

#444 KON-392 Add `withName()` And `withoutName()` Extensions On KoNameProvider List
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoNameProviderListExt.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoNameProviderListExtTest.kt
Labels: minor-api-change

#449 KON-395 Update `toString` To Use Name
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/KoAnnotationDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/KoEnumConstantDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/KoImportDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koinitblock/KoInitBlockDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kokdoc/KoKDocDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kokdoc/snippet/forgeneral/kdoc-to-string.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kopackage/KoPackageDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/KoParameterDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/KoParentDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forgeneral/parent-of-class-to-string.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forgeneral/parent-of-interface-to-string.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forgeneral/parent-of-object-to-string.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koprimaryconstructor/KoPrimaryConstructorDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kosecondaryconstructor/KoSecondaryConstructorDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/KoTypeDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypealias/KoTypeAliasDeclarationTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoAnnotationDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoBaseDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoClassDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoConstructorDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoEnumConstantDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoFileDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoFunctionDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoImportDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoInitBlockDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoInterfaceDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoObjectDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoPackageDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoParameterDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoParentDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoPropertyDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoTypeAliasDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoTypeDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoAnnotationDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoClassDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoEnumConstantDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFunctionDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoImportDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoInitBlockDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoInterfaceDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoKDocDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoObjectDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPackageDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParameterDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentClassDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentInterfaceDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPrimaryConstructorDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPropertyDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoSecondaryConstructorDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoTypeAliasDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoTypeDeclarationCore.kt
Labels: major-api-change

#450 KON-400 Add KoLocationProvider And KoPathProvider To KoKDocDeclaration
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kokdoc/KoKDocDeclarationForKoLocationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kokdoc/KoKDocDeclarationForKoPathProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kokdoc/KoKDocDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kokdoc/snippet/forkolocationprovider/kdoc-location-with-single-digit.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kokdoc/snippet/forkolocationprovider/kdoc-location-with-text.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kokdoc/snippet/forkopathprovider/kdoc-file-path.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kokdoc/snippet/forkopathprovider/kdoc-project-file-path.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kokdoc/snippet/forkopathprovider/kdoc-reside-in-file-path.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kokdoc/snippet/forkopathprovider/kdoc-reside-in-project-file-path.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoKDocDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoKDocDeclarationCore.kt
Labels: minor-api-change

#455 KON-398 Update Starter Projects Readmes
  .github/workflows/check-starter-projects.yml
  samples/starter-projects/README.md
  samples/starter-projects/konsist-starter-android-gradle-groovy-junit-4/README.md
  samples/starter-projects/konsist-starter-android-gradle-groovy-junit-4/app/build.gradle
  samples/starter-projects/konsist-starter-android-gradle-groovy-junit-4/konsist_test/.gitignore
  samples/starter-projects/konsist-starter-android-gradle-groovy-junit-4/konsist_test/build.gradle
  samples/starter-projects/konsist-starter-android-gradle-groovy-junit-4/konsist_test/proguard-rules.pro
  samples/starter-projects/konsist-starter-android-gradle-groovy-junit-4/konsist_test/src/main/AndroidManifest.xml
  samples/starter-projects/konsist-starter-android-gradle-groovy-junit-4/konsist_test/src/test/java/com/sample/SampleKonsistTest.kt
  samples/starter-projects/konsist-starter-android-gradle-groovy-junit-4/settings.gradle
  samples/starter-projects/konsist-starter-android-gradle-groovy-junit-5/README.md
  samples/starter-projects/konsist-starter-android-gradle-groovy-junit-5/app/build.gradle
  samples/starter-projects/konsist-starter-android-gradle-groovy-junit-5/konsist_test/.gitignore
  samples/starter-projects/konsist-starter-android-gradle-groovy-junit-5/konsist_test/build.gradle
  samples/starter-projects/konsist-starter-android-gradle-groovy-junit-5/konsist_test/proguard-rules.pro
  samples/starter-projects/konsist-starter-android-gradle-groovy-junit-5/konsist_test/src/main/AndroidManifest.xml
  samples/starter-projects/konsist-starter-android-gradle-groovy-junit-5/konsist_test/src/test/java/com/sample/SampleKonsistTest.kt
  samples/starter-projects/konsist-starter-android-gradle-groovy-junit-5/settings.gradle
  samples/starter-projects/konsist-starter-android-gradle-kotlin-junit-4/README.md
  samples/starter-projects/konsist-starter-android-gradle-kotlin-junit-4/app/build.gradle.kts
  samples/starter-projects/konsist-starter-android-gradle-kotlin-junit-4/konsist_test/.gitignore
  samples/starter-projects/konsist-starter-android-gradle-kotlin-junit-4/konsist_test/build.gradle.kts
  samples/starter-projects/konsist-starter-android-gradle-kotlin-junit-4/konsist_test/proguard-rules.pro
  samples/starter-projects/konsist-starter-android-gradle-kotlin-junit-4/konsist_test/src/main/AndroidManifest.xml
  samples/starter-projects/konsist-starter-android-gradle-kotlin-junit-4/konsist_test/src/test/java/com/sample/SampleKonsistTest.kt
  samples/starter-projects/konsist-starter-android-gradle-kotlin-junit-4/settings.gradle.kts
  samples/starter-projects/konsist-starter-android-gradle-kotlin-junit-5/README.md
  samples/starter-projects/konsist-starter-android-gradle-kotlin-junit-5/app/build.gradle.kts
  samples/starter-projects/konsist-starter-android-gradle-kotlin-junit-5/konsist_test/.gitignore
  samples/starter-projects/konsist-starter-android-gradle-kotlin-junit-5/konsist_test/build.gradle.kts
  samples/starter-projects/konsist-starter-android-gradle-kotlin-junit-5/konsist_test/proguard-rules.pro
  samples/starter-projects/konsist-starter-android-gradle-kotlin-junit-5/konsist_test/src/main/AndroidManifest.xml
  samples/starter-projects/konsist-starter-android-gradle-kotlin-junit-5/konsist_test/src/test/java/com/sample/SampleKonsistTest.kt
  samples/starter-projects/konsist-starter-android-gradle-kotlin-junit-5/settings.gradle.kts
  samples/starter-projects/konsist-starter-multiplatform-gradle-kotlin-junit5/README.md
  samples/starter-projects/konsist-starter-spring-gradle-groovy-junit-5/README.md
  samples/starter-projects/konsist-starter-spring-gradle-kotlin-junit-5/README.md
  samples/starter-projects/konsist-starter-spring-maven-junit5/README.md
Labels: documentation

#468 Upd Readme
  DeveloperReadme.md
  README.md
Labels: documentation

#475 Update README.md
  README.md
Labels: documentation

#476 Add `files reside in package that is derived from module name` snippet
  lib/src/snippet/kotlin/com/lemonappdev/konsist/ArchitectureSnippets.kt
Labels: documentation

#482 KON-410 KoReceiverTypeProvider Add `hasReceiverTypeOf` And `hasReceiverType(lambda)`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoReceiverTypeProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationForKoReceiverTypeProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoPropertyTypeProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoReceiverTypeProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoPropertyTypeProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoReceiverTypeProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoReceiverTypeProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/util/ReceiverUtil.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoPropertyTypeProviderListExtTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoReceiverTypeProviderListExtTest.kt
Labels: path-api-change

#471 KON-387 Change `includeNested` And `includeLocal` Default Value To True
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoClassProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoFunctionProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoInterfaceProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoObjectProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoPropertyProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/KoFileDeclarationForKoClassProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/KoFileDeclarationForKoDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/KoFileDeclarationForKoFunctionProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/KoFileDeclarationForKoInterfaceProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/KoFileDeclarationForKoObjectProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/KoFileDeclarationForKoPropertyProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoClassProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoFunctionProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoInterfaceProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoObjectProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoPropertyProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoClassProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoFunctionProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoInterfaceProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoObjectProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoPropertyProviderTest.kt
  lib/src/konsistTest/kotlin/com/lemonappdev/konsist/api/ApiKonsistTest.kt
  lib/src/konsistTest/kotlin/com/lemonappdev/konsist/core/DeclarationKonsistTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/container/KoScope.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/koscope/KoScopeExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoClassProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoDeclarationProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoFunctionProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoInterfaceProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoObjectProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoPropertyProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/provider/KoDeclarationProviderExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoClassProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoDeclarationProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoFunctionProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoInterfaceProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoObjectProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoPropertyProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoClassProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoFunctionProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoInterfaceProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoObjectProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoPropertyProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/util/KoDeclarationProviderCoreUtil.kt
  lib/src/snippet/kotlin/com/lemonappdev/konsist/LibrarySnippets.kt
Labels: major-api-change

#485 KON-406 KoReturnTypeProvider Add `hasReturnTypeOf` And `hasReturnType(lambda)`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koreceivertype/KoReceiverTypeProviderExtTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koreceivertype/snippet/declaration-has-no-receiver-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koreturntype/KoReturnTypeProviderExtTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koreturntype/snippet/declaration-has-no-return-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koreturntype/snippet/declaration-has-return-type-with-complex-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koreturntype/snippet/declaration-has-return-type-with-simple-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoReturnTypeProviderTest.kt
  lib/src/konsistTest/kotlin/com/lemonappdev/konsist/api/ApiKonsistTest.kt
  lib/src/konsistTest/kotlin/com/lemonappdev/konsist/core/DeclarationKonsistTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoReturnTypeProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/provider/KoPropertyTypeProviderExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/provider/KoReceiverTypeProviderExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/provider/KoReturnTypeProviderExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoReturnTypeProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoReturnTypeProviderCore.kt
  lib/src/snippet/kotlin/com/lemonappdev/konsist/LibrarySnippets.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoReturnTypeProviderListExtTest.kt
Labels: path-api-change

#491 KON-423 KoArgumentProvider Add `hasArgument(lambda)` `hasAllArguments(lambda)` And `countArguments(lambda)`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/KoAnnotationDeclarationForKoArgumentProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/KoEnumConstantDeclarationForKoArgumentProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoArgumentProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoArgumentProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoArgumentProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoArgumentProviderListExtTest.kt
Labels: path-api-change

#496 KON-414 Add Extensions To Expose `tags`
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoKDocTagsProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoKDocTagsProvider.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoKDocTagsProviderListExtTest.kt
Labels: path-api-change

#495 KON-418 Add Message To `assert` And `assertNot`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertForDeclarationListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertForDeclarationSequenceTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/snippet/declaration-assert-error-with-custom-message.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/snippet/file-declaration-assert-error-with-custom-message.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/KoDeclarationAssertForProviderListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/KoDeclarationAssertForProviderSequenceTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/snippet/provider-assert-error-with-custom-message.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/verify/KoDeclarationAndProviderAssert.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/CommonAssert.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt
Labels: path-api-change

#497 KON-417 Add Provider With `matches` Method
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/KoImportDeclarationForKoMatchesProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/snippet/forkomatchesprovider/import-matches.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoImportDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoMatchesProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoImportDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoMatchesProviderCore.kt
Labels: path-api-change

#499 Update Assert Error Message
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertForDeclarationListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertForDeclarationSequenceTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/KoDeclarationAssertForProviderListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/KoDeclarationAssertForProviderSequenceTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt
Labels: path-api-change

#507 Update Assert Error Message
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertForDeclarationListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/KoDeclarationAssertForDeclarationSequenceTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt
  lib/src/snippet/kotlin/com/lemonappdev/konsist/ArchitectureSnippets.kt
Labels: path-api-change

#513 KON-422 KoAnnotationProvider Add `hasAnnotation(lambda)` And `hasAllAnnotations`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koconstructor/KoConstructorDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/KoEnumConstantDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/KoFileDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/KoParameterDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationForKoAnnotationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypealias/KoTypeAliasDeclarationForKoAnnotationProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoAnnotationProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoAnnotationProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoAnnotationProviderCore.kt
  lib/src/snippet/kotlin/com/lemonappdev/konsist/TestSnippets.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoAnnotationProviderListExtTest.kt
Labels: path-api-change

#511 KON-437 Update KoImportProvider `hasImport` Methods
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/KoFileDeclarationForKoImportProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/snippet/forkoimportprovider/file-has-no-import.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/snippet/forkoimportprovider/file-has-one-import.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/snippet/forkoimportprovider/file-has-two-imports.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoImportProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoImportProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoImportProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoImportProviderListExtTest.kt
Labels: path-api-change

#510 KON-436 Update KoEnumConstantProvider `hasEnumConstant` Methods
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoEnumConstantProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/snippet/forkoenumconstantprovider/class-has-one-constant.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/snippet/forkoenumconstantprovider/class-has-two-constants.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoEnumConstantProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoEnumConstantProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoEnumConstantProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoEnumConstantProviderListExtTest.kt
Labels: path-api-change

#506 KON-433 Update KoArgumentProvider `hasArgument` Methods
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/KoAnnotationDeclarationForKoArgumentProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/KoEnumConstantDeclarationForKoArgumentProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkoargument/enum-const-with-one-argument.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkoargument/enum-const-with-two-arguments.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoArgumentProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoArgumentProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoArgumentProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoArgumentProviderListExtTest.kt
Labels: path-api-change

#505 KON-430 KoTypeAliasProvider Add `hasTypeAlias` Methods
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/KoFileDeclarationForKoTypeAliasProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/snippet/forkotypealiasprovider/file-has-one-typealias.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/snippet/forkotypealiasprovider/file-has-two-typealiases.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoTypeAliasProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoTypeAliasProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoTypeAliasProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoTypeAliasProviderListExtTest.kt
Labels: path-api-change

#503 KON-429 KoSecondaryConstructorProvider Add `hasSecondaryConstructor` Methods
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoSecondaryConstructorsProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/snippet/forkosecondaryconstructorsprovider/class-has-one-secondary-constructor.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/snippet/forkosecondaryconstructorsprovider/class-has-two-secondary-constructors.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoSecondaryConstructorsProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoSecondaryConstructorsProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoSecondaryConstructorsProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoSecondaryConstructorsProviderListExtTest.kt
Labels: path-api-change

#502 KON-427 KoParametersProvider Add `hasParameter` Methods
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koconstructor/KoConstructorDeclarationForKoParametersProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koconstructor/snippet/forkoparametersprovider/constructor-contains-one-parameter.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koconstructor/snippet/forkoparametersprovider/constructor-contains-two-parameters.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoParametersProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoparametersprovider/function-contains-one-parameter.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoparametersprovider/function-contains-two-parameters.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoParametersProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoParametersProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoParametersProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoParametersProviderListExtTest.kt
Labels: path-api-change

#501 KON-426 KoInitBlockProvider Add `hasInitBlock` Methods
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoInitBlockProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoInitBlockProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoInitBlockProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoInitBlockProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoInitBlockProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoInitBlockProviderListExtTest.kt
Labels: path-api-change

#500 KON-428 KoParentProvider Add `hasParent` Methods
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoParentProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoParentProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoParentProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoParentProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoParentProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoParentProviderCore.kt
  lib/src/snippet/kotlin/com/lemonappdev/konsist/CleanArchitectureSnippets.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoParentProviderListExtTest.kt
Labels: path-api-change

#517 KON-439 Remove KoVisibilityModifierProvider From KoParameterDeclaration
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koconstructor/KoConstructorDeclarationForKoParametersProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoParametersProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/forkomodifier/KoParameterDeclarationForKoVisibilityModifierProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/forkomodifier/snippet/forkovisibilitymodifierprovider/parameter-has-internal-modifier.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/forkomodifier/snippet/forkovisibilitymodifierprovider/parameter-has-no-visibility-modifiers.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/forkomodifier/snippet/forkovisibilitymodifierprovider/parameter-has-private-modifier.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/forkomodifier/snippet/forkovisibilitymodifierprovider/parameter-has-protected-modifier.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/forkomodifier/snippet/forkovisibilitymodifierprovider/parameter-has-public-modifier.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/forkomodifier/snippet/forkovisibilitymodifierprovider/parameter-is-public-by-default.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoParameterDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParameterDeclarationCore.kt
Labels: major-api-change

#516 KON-432 Add `hasParentOf` Methods And Rename Extensions
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparent/KoParentProviderExtTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparent/snippet/class-has-two-parents-with-imports.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparent/snippet/class-has-two-parents-without-imports.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparent/snippet/interface-has-parent-with-import.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparent/snippet/interface-has-parent-without-import.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparent/snippet/object-has-two-parents-with-imports.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparent/snippet/object-has-two-parents-without-imports.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoParentProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoParentProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoParentProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/testdata/TestData.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoParentProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/provider/KoParentProviderExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoParentProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoParentProviderCore.kt
  lib/src/snippet/kotlin/com/lemonappdev/konsist/AndroidSnippets.kt
  lib/src/snippet/kotlin/com/lemonappdev/konsist/TestSnippets.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoParentProviderListExtTest.kt
Labels: path-api-change

#504 Add regex pattern to deal with ending (only) 2 dots at the end of package name
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture5/Architecture5Test.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/Layer.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/util/LocationUtil.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/architecture/LayerTest.kt
Labels: improvement

#523 KON-443 Ignore Dot Gradle Directory
  lib/src/main/kotlin/com/lemonappdev/konsist/core/container/KoScopeCreatorCore.kt
  test-projects/konsist-path-tester/.gradle/caches/GradleCachedKotlinClass.kt
Labels: bug

#563 KON-447 Add Konsist Test To Check If All `hasX` Methods Are In Provider
  lib/src/konsistTest/kotlin/com/lemonappdev/konsist/api/ApiKonsistTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoConstructorProviderListExt.kt
Labels: improvement

#570 KON-461 Remove Double Suppression Check
  lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt
Labels: improvement

#573 Update Dev Readme
  DeveloperReadme.md
Labels: documentation

#565 KON-457 KoConstructorProviderListExt Change `withConstructor` To `withConstructors` And `withoutConstructor` To `withoutConstructors`
  lib/src/konsistTest/kotlin/com/lemonappdev/konsist/api/ApiKonsistTest.kt
  lib/src/konsistTest/kotlin/com/lemonappdev/konsist/core/DeclarationKonsistTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoConstructorProviderListExt.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoConstructorProviderListExtTest.kt
Labels: path-api-change

#588 KON-480 Add `scopeFromFiles()`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/TestSnippetProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/container/KoScopeCreator.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/container/KoScopeCreatorCore.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/container/from/KoScopeFromFileTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koannotation/KoAnnotationForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koannotation/KoAnnotationForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koargument/KoArgumentForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koargument/KoArgumentForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koclass/KoClassForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koclass/KoClassForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koconstructor/KoConstructorForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koconstructor/KoConstructorForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koenumconstant/KoEnumConstantForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koenumconstant/KoEnumConstantForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kofile/KoFileForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kofile/KoFileForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kofunction/KoFunctionForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kofunction/KoFunctionForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koimport/KoImportForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koimport/KoImportForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koinitblock/KoInitBlockForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koinitblock/KoInitBlockForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kointerface/KoInterfaceForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kointerface/KoInterfaceForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kokdoc/KoKDocForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kokdoc/KoKDocForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koobject/KoObjectForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koobject/KoObjectForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kopackage/KoPackageForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kopackage/KoPackageForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koparameter/KoParameterForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koparameter/KoParameterForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koparent/KoParentForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koparent/KoParentForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koproperty/KoPropertyForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koproperty/KoPropertyForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kotype/KoTypeForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kotype/KoTypeForKoSourceSetProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kotypealias/KoTypeAliasForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kotypealias/KoTypeAliasForKoSourceSetProviderTest.kt
Labels: improvement

#583 KON-477 Fix Snippets After Change Default Value Of `includeNested` And`includeLocal` Parameters
  lib/src/snippet/kotlin/com/lemonappdev/konsist/GeneralSnippets.kt
Labels: documentation

#580 KON-463 Add `withName{}` And `withoutName{}`
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoNameProviderListExt.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoNameProviderListExtTest.kt
Labels: path-api-change

#567 KON-453 Fix Broken `fullyQualifiedName`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/KoAnnotationDeclarationForKoContainingFileProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/KoAnnotationDeclarationForKoFullyQualifiedNameProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/snippet/forkocontainingfileprovider/annotation-in-file-containing-file.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/snippet/forkofullyqualifiednameprovider/annotation-fully-qualified-name-where-annotation-is-defined-in-the-same-file-with-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/snippet/forkofullyqualifiednameprovider/annotation-fully-qualified-name-where-annotation-is-defined-in-the-same-file-without-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/snippet/forkofullyqualifiednameprovider/annotation-fully-qualified-name-without-import.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/snippet/forkofullyqualifiednameprovider/annotation-in-file-fully-qualified-name-where-annotation-is-defined-in-the-same-file-with-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/snippet/forkofullyqualifiednameprovider/annotation-in-file-fully-qualified-name-where-annotation-is-defined-in-the-same-file-without-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koannotation/snippet/forkofullyqualifiednameprovider/annotation-in-file-fully-qualified-name.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoFullyQualifiedNameProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/snippet/forkodeclarationfullyqualifiednameprovider/nested-class-fully-qualified-name-without-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/snippet/forkodeclarationfullyqualifiednameprovider/nested-class-fully-qualified-name.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/KoEnumConstantDeclarationForKoFullyQualifiedNameProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkodeclarationfullyqualifiednameprovider/nested-enum-const-fully-qualified-name-without-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkodeclarationfullyqualifiednameprovider/nested-enum-const-fully-qualified-name.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoFullyQualifiedNameProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkodeclarationfullyqualifiednameprovider/nested-function-fully-qualified-name-without-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkodeclarationfullyqualifiednameprovider/nested-function-fully-qualified-name.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoFullyQualifiedNameProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/snippet/forkodeclarationfullyqualifiednameprovider/nested-interface-fully-qualified-name-without-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/snippet/forkodeclarationfullyqualifiednameprovider/nested-interface-fully-qualified-name.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoFullyQualifiedNameProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/snippet/forkodeclarationfullyqualifiednameprovider/nested-object-fully-qualified-name-without-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/snippet/forkodeclarationfullyqualifiednameprovider/nested-object-fully-qualified-name.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/KoParameterDeclarationForKoFullyQualifiedNameProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/snippet/forkodeclarationfullyqualifiednameprovider/nested-parameter-fully-qualified-name-without-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/snippet/forkodeclarationfullyqualifiednameprovider/nested-parameter-fully-qualified-name.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/KoParentDeclarationForKoFullyQualifiedNameProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/nested-parent-of-class-fully-qualified-name-with-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/nested-parent-of-class-fully-qualified-name-without-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/nested-parent-of-interface-fully-qualified-name-with-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/nested-parent-of-interface-fully-qualified-name-without-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/nested-parent-of-object-fully-qualified-name-with-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/nested-parent-of-object-fully-qualified-name-without-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/parent-of-class-fully-qualified-name-with-import.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/parent-of-class-fully-qualified-name-without-import-and-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/parent-of-class-fully-qualified-name-without-import-and-with-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/parent-of-interface-fully-qualified-name-with-import.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/parent-of-interface-fully-qualified-name-without-import-and-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/parent-of-interface-fully-qualified-name-without-import-and-with-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/parent-of-object-fully-qualified-name-with-import.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/parent-of-object-fully-qualified-name-without-import-and-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkofullyqualifiednameprovider/parent-of-object-fully-qualified-name-without-import-and-with-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationForKoFullyQualifiedNameProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkodeclarationfullyqualifiednameprovider/nested-property-fully-qualified-name-without-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkodeclarationfullyqualifiednameprovider/nested-property-fully-qualified-name.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/KoTypeDeclarationForKoFullyQualifiedNameProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/non-nullable-type-in-nested-classes-with-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/non-nullable-type-in-nested-classes-without-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/non-nullable-type-without-import-and-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/non-nullable-type-without-import-and-with-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/nullable-type-in-nested-classes-with-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/nullable-type-in-nested-classes-without-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/nullable-type-without-import-and-package.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotype/snippet/forkofullyqualifiednameprovider/nullable-type-without-import-and-with-package.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoAnnotationDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoFullyQualifiedNameProviderCore.kt
Labels: bug

#601 KON-489 Add `KoTest` Dependency To `integrationTest`
  lib/build.gradle.kts
Labels: improvement

#604 Run Starter Projects Check For Updates Triggered By Renovate
  .github/workflows/check-starter-projects.yml
Labels: improvement

#605 Update Dev Readme
  DeveloperReadme.md
Labels: documentation

#612 Update Readme
  DeveloperReadme.md
Labels: documentation

#621 Update Script Trigger
  .github/workflows/check-starter-projects.yml
Labels: improvement

#617 KON-498 Remove Snippet `companion objects are last declarations in the class`
  lib/src/snippet/kotlin/com/lemonappdev/konsist/GeneralSnippets.kt
Labels: documentation

#633 Update comment
  buildSrc/src/main/kotlin/local.javalibrary.gradle.kts
Labels: documentation

#636 Update Triggers For GitHub Action Snippets
  .github/workflows/check-kttxt-snippets.yml
  .github/workflows/check-starter-projects.yml
  .github/workflows/check.yml
Labels: improvement

#638 KON-501 Verify JVM Bytecode Version
  .github/workflows/check-kttxt-snippets.yml
  .github/workflows/check-starter-projects.yml
  .github/workflows/check.yml
  scripts/check_bytecode_version.py
  scripts/check_dependencies_exposed_by_library_artifact.py
  scripts/check_kttxt_snippets.py
  scripts/get_artifact_path.py
  scripts/get_konsist_version.py
  scripts/konsist-0.12.2-SNAPSHOT-javadoc.jar
  scripts/replace-konsist-version/add_maven_local_repository_to_config_file.py
  scripts/replace-konsist-version/replace_konsist_version_gradle_groovy.py
  scripts/update_snippets.py
Labels: improvement

#643 Update Ci Setup
  .github/workflows/check-starter-projects.yml
Labels: improvement

#652 KON-507 Add `hasExpressionBody` And `hasBlockBody` To KoFunctionDeclaration
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoBodyProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkobodyprovider/function-has-block-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkobodyprovider/function-has-expression-body.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoFunctionDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoBodyProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoBodyProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFunctionDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoBodyProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoBodyProviderListExtTest.kt
Labels: improvement

#657 KON-203 Add `hasReturnValue` To KoFunctionDeclaration
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoReturnTypeProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturntypeprovider/function-with-block-body-and-declared-type-has-string-return-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturntypeprovider/function-with-block-body-and-declared-type-has-unit-return-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturntypeprovider/function-with-block-body-and-without-declared-type-has-unit-return-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturntypeprovider/function-with-expression-body-and-declared-type-has-string-return-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturntypeprovider/function-with-expression-body-and-declared-type-has-unit-return-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturntypeprovider/function-with-expression-body-and-without-declared-type-has-string-return-value.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoreturntypeprovider/function-with-expression-body-and-without-declared-type-has-unit-return-value.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoReturnTypeProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoReturnTypeProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoReturnTypeProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoReturnTypeProviderListExtTest.kt
Labels: improvement

#663 Update Snippet
  lib/src/snippet/kotlin/com/lemonappdev/konsist/JUnitSnippets.kt
Labels: documentation
