Repository LemonAppDev/konsist, pull requests merged in 2024-11, with the labels that each got.

#1506 KON-678 Add Layer Include
  detekt.yml
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture1/Architecture1Test.kt
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture2/Architecture2Test.kt
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture4/Architecture4Test.kt
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture5/Architecture5Test.kt
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture7/Architecture7Test.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/LayerDependencies.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/LayerDependenciesCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/LayerDependencyType.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoArchitectureAssert.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/core/architecture/LayerDependenciesCoreTest.kt
Labels: improvement

#1507 KON-679 Allow To Call Layer Dependency Method On Collections
  lib/src/konsistTest/kotlin/com/lemonappdev/konsist/core/EnumKonsistTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/LayerDependencies.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/LayerDependenciesCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/LayerDependency.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/LayerDependencyType.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/validator/rule/CircularDependencyDependenciesRule.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/validator/rule/DependOnLayerThenDependentOnNothingRule.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/validator/rule/DependentOnNothingThenDependOnLayerDependenciesRule.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/core/architecture/LayerDependenciesCoreTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/core/architecture/LayerDependencyTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/core/architecture/validator/rule/CircularDependencyDependenciesRuleTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/core/architecture/validator/rule/DependOnLayerThenDependentOnNothingRuleTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/core/architecture/validator/rule/DependentOnNothingThenDependOnLayerDependenciesRuleTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/core/architecture/validator/rule/UniqueLayerRuleTest.kt
Labels: improvement

#1499 KON-658 Change structure of parameter types in KoFunctionTypeDeclarationProvider
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/KoTypeArgumentDeclarationForKoFunctionTypeDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/snippet/forkofunctiontypedeclarationprovider/parameters-list-has-one-element-with-name.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/KoTypeDeclarationForKoFunctionTypeDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkofunctiontypedeclarationprovider/parameters-list-has-one-element-with-name.kttest
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoFunctionTypeDeclarationProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoFunctionTypeDeclarationProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoFunctionTypeDeclarationProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoFunctionTypeDeclarationProviderListExtTest.kt
Labels: improvement

#1508 KON-680 Rename `isGenericType` to `isGeneric`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoTypeParameterProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoTypeParameterProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoTypeParameterProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/KoParentDeclarationForKoDeclarationCastProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/KoParentDeclarationForKoTypeArgumentProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationForKoTypeParameterProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypealias/KoTypeAliasDeclarationForKoTypeParameterProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/KoTypeArgumentDeclarationForKoDeclarationCastProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/KoTypeArgumentDeclarationForKoFunctionTypeDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/KoTypeArgumentDeclarationForKoIsGenericProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/KoTypeArgumentDeclarationForKoSourceDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/KoTypeArgumentDeclarationForKoTypeArgumentProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/snippet/forkoisgenericprovider/class-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/snippet/forkoisgenericprovider/external-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/snippet/forkoisgenericprovider/function-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/snippet/forkoisgenericprovider/generic-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/snippet/forkoisgenericprovider/import-alias-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/snippet/forkoisgenericprovider/interface-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/snippet/forkoisgenericprovider/kotlin-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/snippet/forkoisgenericprovider/object-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/snippet/forkoisgenericprovider/typealias-with-generic-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/snippet/forkoisgenericprovider/typealias-without-generic-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kostarprojection/KoStarProjectionDeclarationForKoDeclarationCastProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/KoTypeDeclarationForKoDeclarationCastProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/KoTypeDeclarationForKoFunctionTypeDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/KoTypeDeclarationForKoIsGenericProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/KoTypeDeclarationForKoTypeArgumentProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoisgenericprovider/external-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoisgenericprovider/function-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoisgenericprovider/generic-class-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoisgenericprovider/generic-import-alias-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoisgenericprovider/generic-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoisgenericprovider/generic-typealias-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoisgenericprovider/interface-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoisgenericprovider/kotlin-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoisgenericprovider/not-generic-class-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoisgenericprovider/not-generic-import-alias-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoisgenericprovider/not-generic-typealias-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoisgenericprovider/object-type.kttest
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoTypeArgumentDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/type/KoTypeDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoDeclarationCastProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoIsGenericProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoIsGenericTypeProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoDeclarationCastProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoGenericTypeProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoIsGenericProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoIsGenericTypeProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoTypeArgumentDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoDeclarationCastProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoExternalParentProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoIsGenericProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoIsGenericTypeProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoDeclarationCastProviderListExtTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoIsGenericProviderListExtTest.kt
Labels: improvement

#1510 KON-681 Add isGeneric for declarations in declaration site
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoIsGenericProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/snippet/forkoisgenericprovider/class-is-generic.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/snippet/forkoisgenericprovider/class-is-not-generic.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/KoFunctionDeclarationForKoIsGenericProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoisgenericprovider/function-is-generic.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofunction/snippet/forkoisgenericprovider/function-is-not-generic.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoIsGenericProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/snippet/forkoisgenericprovider/interface-is-generic.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/snippet/forkoisgenericprovider/interface-is-not-generic.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationForKoIsGenericProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoisgenericprovider/property-is-generic.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoisgenericprovider/property-is-not-generic.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypealias/KoTypeAliasDeclarationForKoIsGenericProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypealias/snippet/forkoisgenericprovider/typealias-is-generic.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypealias/snippet/forkoisgenericprovider/typealias-is-not-generic.kttest
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoClassDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoFunctionDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoInterfaceDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoPropertyDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoTypeAliasDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/combined/KoClassAndInterfaceDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoClassDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFunctionDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoInterfaceDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPropertyDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoTypeAliasDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/combined/KoClassAndInterfaceDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoIsGenericProviderCore.kt
Labels: improvement

#1511 Refactor Asci Tree Node
  lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/validator/ascii/AsciiTreeNode.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoArchitectureAssert.kt
Labels: maintenance

#1512 Unify Dependency Names
  buildSrc/build.gradle.kts
  gradle/libs.versions.toml
  lib/build.gradle.kts
  test-projects/konsist-declaration-tester/app/build.gradle.kts
  test-projects/konsist-declaration-tester/build.gradle.kts
  test-projects/konsist-declaration-tester/data/build.gradle.kts
  test-projects/konsist-declaration-tester/gradle/libs.versions.toml
  test-projects/konsist-path-tester/app/build.gradle.kts
  test-projects/konsist-path-tester/build.gradle.kts
  test-projects/konsist-path-tester/data/build.gradle.kts
  test-projects/konsist-path-tester/gradle/libs.versions.toml
  test-projects/konsist-root-path-gradle-tester/app/build.gradle.kts
  test-projects/konsist-root-path-gradle-tester/build.gradle.kts
  test-projects/konsist-root-path-gradle-tester/gradle/libs.versions.toml
Labels: maintenance

#1514 Rename Fqn To FullyQualifiedName
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/KoTypeDeclarationForKoSourceDeclarationProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/model/DataCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoFullyQualifiedNameProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoSourceDeclarationProviderCore.kt
Labels: maintenance

#1547 KON-685 Add missing declaration in KoDeclarationCastProvider for combined types
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/KoParentDeclarationForKoDeclarationCastProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kotypeargument/KoTypeArgumentDeclarationForKoDeclarationCastProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kostarprojection/KoStarProjectionDeclarationForKoDeclarationCastProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/KoTypeDeclarationForKoDeclarationCastProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoDeclarationCastProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoDeclarationCastProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoDeclarationCastProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoDeclarationCastProviderListExtTest.kt
Labels: improvement

#1515 KON-677 Fix snippets in GenericTypesSnippets
  .github/workflows/check-ktdoc-snippets.yml
  lib/src/snippet/kotlin/com/lemonappdev/konsist/AndroidSnippets.ktdoc
  lib/src/snippet/kotlin/com/lemonappdev/konsist/GeneralSnippets.ktdoc
  lib/src/snippet/kotlin/com/lemonappdev/konsist/GenericTypesSnippets.ktdoc
  lib/src/snippet/kotlin/com/lemonappdev/konsist/SpringSnippets.ktdoc
Labels: documentation

#1583 KON-692 Fix "StackOverflowError" Exception when trying to find indirect parents
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/KoParentDeclarationForKoSourceDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/class-with-parent-class-with-the-same-name.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/class-with-parent-interface-with-the-same-name.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/interface-with-parent-interface-with-the-same-name.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/object-with-parent-class-with-the-same-name.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/object-with-parent-interface-with-the-same-name.kttest
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/model/DataCore.kt
Labels: bug-fix

#1586 KON-693 Add ASCII tree to missing methods like assertNotEmpty
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/assertempty/AssertEmptyOnDeclarationListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/assertempty/AssertEmptyOnDeclarationSequenceTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/assertempty/AssertEmptyOnProviderListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/assertempty/AssertEmptyOnProviderSequenceTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt
Labels: improvement
