Repository LemonAppDev/konsist, pull requests merged in 2024-02, with the labels that each got.

#837 Rename `koTest` to `Kotest`
  .github/workflows/check-starter-projects.yml
  gradle/libs.versions.toml
  lib/build.gradle.kts
  lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/KoArchitectureAssertion.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/verify/KoDeclarationAndProviderAssert.kt
  samples/starter-projects/konsist-starter-android-gradle-groovy-kotest/README.md
  samples/starter-projects/konsist-starter-android-gradle-kotlin-kotest/README.md
  samples/starter-projects/konsist-starter-spring-gradle-groovy-kotest/README.md
  samples/starter-projects/konsist-starter-spring-gradle-groovy-kotest/build.gradle
  samples/starter-projects/konsist-starter-spring-gradle-kotlin-kotest/README.md
  samples/starter-projects/konsist-starter-spring-gradle-kotlin-kotest/build.gradle.kts
  samples/starter-projects/konsist-starter-spring-maven-kotest/README.md
Labels: documentation

#736 KON-367 Add Child Declaration References
  .github/workflows/check-kttxt-snippets.yml
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparentclass/snippet/class-has-parent-class-defined-in-the-same-file.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparentclass/snippet/class-has-parent-class-imported-from-external-file.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparentinterface/KoParentInterfaceProviderExtTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparentinterface/snippet/class-has-parent-interface-defined-in-the-same-file.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparentinterface/snippet/class-has-parent-interface-imported-from-external-file.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparentinterface/snippet/interface-has-parent-interface-defined-in-the-same-file.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparentinterface/snippet/interface-has-parent-interface-imported-from-external-file.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparentinterface/snippet/object-has-parent-interface-defined-in-the-same-file.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparentinterface/snippet/object-has-parent-interface-imported-from-external-file.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoChildDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoClassDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoExternalParentDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoInterfaceDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoObjectDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoChildProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoChildProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/container/KoScopeCreatorCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoChildDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoClassDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoExternalParentDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoInterfaceDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoObjectDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/model/DataCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoChildProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoExternalParentProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoParentClassProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoParentInterfaceProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoParentProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/util/KClassUtil.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/util/ParentUtil.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoChildProviderListExtTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/container/from/KoScopeFromModuleTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/container/from/KoScopeFromProjectTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/container/from/KoScopeFromSourceSetTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/container/from/KoScopeFromTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kochild/KoChildDeclarationForKoFullyQualifiedNameProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kochild/KoChildDeclarationForKoNameProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kochild/KoChildDeclarationForKoPackageProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kochild/KoChildDeclarationForKoResideInPackageProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koclass/KoClassForKoChildProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koimport/KoImportForKoModuleProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kointerface/KoInterfaceForKoChildProviderTest.kt
  test-projects/konsist-path-tester/app/src/main/kotlin/com/lemonappdev/sample/AppClass.kt
Labels: improvement

#855 Remove Scope Violation Suppress
  test-projects/konsist-path-tester/build.gradle.kts
  test-projects/konsist-root-path-gradle-tester/build.gradle.kts
Labels: improvement

#854 Upgrade CI Java Version
  .github/workflows/check-kttxt-snippets.yml
  .github/workflows/check-starter-projects.yml
  .github/workflows/check.yml
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/local.kotlin.gradle.kts
  test-projects/konsist-path-tester/app/build.gradle.kts
  test-projects/konsist-path-tester/build.gradle.kts
  test-projects/konsist-path-tester/data/build.gradle.kts
  test-projects/konsist-root-path-gradle-tester/app/build.gradle.kts
  test-projects/konsist-root-path-gradle-tester/build.gradle.kts
Labels: CI

#784 KON-368 Add Tests Declaration References
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoHasTestClassProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoTestClassProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoClassDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoHasTestClassProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoTestClassProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoHasTestClassProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoHasTestProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoTestClassProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoClassDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoFullyQualifiedNameProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoHasTestClassProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoHasTestProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoTestClassProviderCore.kt
  lib/src/snippet/kotlin/com/lemonappdev/konsist/JUnitSnippets.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoHasTestClassProviderListExtTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoTestClassProviderListExtTest.kt
  test-projects/konsist-path-tester/app/build.gradle.kts
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/container/KoScopeTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/container/from/KoScopeFromModuleTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/container/from/KoScopeFromPackageTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/container/from/KoScopeFromProjectTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/container/from/KoScopeFromSourceSetTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/container/from/KoScopeFromTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koclass/KoClassDeclarationForKoHasTestClassProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/koclass/KoClassDeclarationForKoTestClassProviderTest.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/sample/AppTestClasses.kt
  test-projects/konsist-path-tester/app/src/main/kotlin/com/lemonappdev/sample/AppClass.kt
  test-projects/konsist-path-tester/data/src/test/kotlin/com/lemonappdev/sample/LibTestClasses.kt
  test-projects/konsist-path-tester/data/src/test/kotlin/com/lemonappdev/sample/data/LibDataClassTest.kt
  test-projects/konsist-path-tester/gradle/libs.versions.toml
  test-projects/konsist-root-path-gradle-tester/gradle/libs.versions.toml
Labels: breaking-api-change, improvement
