Repository LemonAppDev/konsist, pull requests merged in 2024-03, with the labels that each got.

#877 Add Slack Badge
  README.md
Labels: documentation

#773 KON-543 Add `hasTacitType`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/kotacittype/KoTacitTypeProviderExtTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/kotacittype/snippet/declaration-has-explicit-complex-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/kotacittype/snippet/declaration-has-explicit-simple-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/kotacittype/snippet/declaration-has-implicit-complex-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/kotacittype/snippet/declaration-has-no-tacit-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationForKoTacitTypeProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkotacittypeprovider/property-has-explicit-complex-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkotacittypeprovider/property-has-explicit-simple-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkotacittypeprovider/property-has-implicit-complex-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkotacittypeprovider/property-has-no-tacit-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kovariable/KoVariableDeclarationForKoTacitTypeProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kovariable/snippet/forkotacittypeprovider/variable-has-explicit-complex-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kovariable/snippet/forkotacittypeprovider/variable-has-explicit-simple-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kovariable/snippet/forkotacittypeprovider/variable-has-implicit-complex-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kovariable/snippet/forkotacittypeprovider/variable-has-no-tacit-type.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoPropertyDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoVariableDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoTacitTypeProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/provider/KoTacitTypeProviderExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoTacitTypeProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPropertyDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoVariableDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoTacitTypeProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoTacitTypeProviderListExtTest.kt
Labels: improvement

#880 KON-589 Upload Check results as artifacts
  .github/workflows/check.yml
Labels: CI

#881 KON-591 Run path test projects on MacOs
  .github/workflows/check.yml
Labels: CI

#882 KON-590 Root Path Testers Are Failin On Ubuntu
  .github/workflows/check-kttxt-snippets.yml
  .github/workflows/check-path.yml
  .github/workflows/check.yml
Labels: CI

#895 KON-601 Update KDoc for `isInitialized` property
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationForKoInitializerProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoinitializerprovider/property-with-delegate-is-initialized-in-block-body.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoinitializerprovider/property-with-lateinit-modifier-is-not-initialized.kttxt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoInitializerProvider.kt
Labels: improvement

#893 KON-593 `KoPackageMatchingPathProviderCore.hasMatchingPath` fails on windows
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoPackageMatchingPathProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/util/PathUtil.kt
  test-projects/konsist-declaration-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/kopackage/KoPackageDeclarationForKoPackageMatchingPathProviderTest.kt
  test-projects/konsist-declaration-tester/app/src/main/kotlin/com/lemonappdev/sample/AppClassWithPackageNotMatchingToPath.kt
  test-projects/konsist-path-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/helper/ext/PathExt.kt
Labels: bug-fix

#897 KON-602 Improve layer verification
  lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/Layer.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/util/LocationUtil.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/architecture/LayerTest.kt
Labels: improvement

#898 Update Dev Readme
  DeveloperReadme.md
Labels: CI

#901 KON-604 Update Artifact Verification
  .github/workflows/check.yml
  scripts/check_konsist_artifact_bytecode_version.py
Labels: CI

#900 KON-596 Add extensions to retrieve properties of the source type
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/KoTypeDeclarationForKoSourceDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/KoTypeDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-class-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-external-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-function-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-import-alias-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-interface-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-kotlin-basic-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-kotlin-collection-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-object-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/not-nullable-typealias-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-class-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-external-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-function-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-import-alias-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-interface-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-kotlin-basic-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-kotlin-collection-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-object-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkosourcedeclarationprovider/nullable-typealias-type.kttxt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/testdata/TestData.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/type/KoTypeDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoSourceDeclarationProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoSourceDeclarationProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoSourceDeclarationProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoSourceDeclarationProviderListExtTest.kt
Labels: improvement

#904 KON-586 Add KDocs for DeclarationReference
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoSourceDeclarationProvider.kt
Labels: documentation, improvement

#909 Rename CI Jobs
  .github/workflows/check-path.yml
  .github/workflows/check.yml
  DeveloperReadme.md
Labels: CI

#915 Update Kdoc
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoSourceDeclarationProvider.kt
Labels: documentation

#926 Add Missing Kotlin Basic Types - `Unit`, `Any` and `Nothing`
  lib/src/main/kotlin/com/lemonappdev/konsist/core/util/TypeUtil.kt
Labels: improvement

#953 Upd Dev Readme
  DeveloperReadme.md
Labels: documentation

#954 KON-614 Update Kotlin Compiler Dependency `kotlin-compiler` to `kotlin-compiler-embeddable`
  .github/workflows/check.yml
  gradle/libs.versions.toml
  lib/build.gradle.kts
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoAnnotationDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoArgumentDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoClassDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoConstructorDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoEnumConstantDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoExternalDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFileDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFunctionDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoGetterDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoImportAliasDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoImportDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoInitBlockDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoInterfaceDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoKDocDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoObjectDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPackageDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParameterDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentClassDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentInterfaceDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPropertyDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoSetterDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoTypeAliasDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoVariableDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoFunctionTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoKotlinTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoPathProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoTextProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/util/KoDeclarationProviderCoreUtil.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/util/KoLocalDeclarationProviderCoreUtil.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/util/KotlinFileParser.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/util/TypeUtil.kt
  scripts/check_dependencies_exposed_by_konsist_artifact.py
Labels: improvement
