Repository LemonAppDev/konsist, pull requests merged in 2024-12, with the labels that each got.

#1598 KON-697 `hasValidKDocParamTags` not distinguish non-KDoc tags
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparameters/KoParametersProviderExtTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/api/ext/provider/koparameters/snippet/declaration-with-non-tag-with-@-in-description-has-valid-kdoc.kttest
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoKDocDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/tag/KoKDocTagProviderCore.kt
Labels: bug-fix

#1597 KON-696 Add missing deprecation for KoTypeDeclaration for extensions from KoDeclarationCastProviderListExt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/DeprecatedKoDeclarationCastProviderListExt.kt
  lib/src/snippet/kotlin/com/lemonappdev/konsist/GeneralSnippets.ktdoc
Labels: documentation

#1600 KON-699 Restore Layer Package Validation
  lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/Layer.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/architecture/LayerTest.kt
Labels: bug-fix

#1618 KON-695 Add missing providers for `KoEnumContantDeclaration`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koclass/KoClassDeclarationForKoDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/KoEnumConstantDeclarationForKoClassProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/KoEnumConstantDeclarationForKoDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/KoEnumConstantDeclarationForKoFunctionProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/KoEnumConstantDeclarationForKoPropertyProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkoclassprovider/enum-constant-contains-class.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkoclassprovider/enum-constant-contains-no-classes.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkodeclarationprovider/enum-constant-contains-declarations.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkodeclarationprovider/enum-constant-contains-nested-and-local-declarations.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkodeclarationprovider/enum-constant-contains-no-declarations.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkofunctionprovider/enum-constant-contains-function.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkofunctionprovider/enum-constant-contains-no-function.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkopropertyprovider/count-properties.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkopropertyprovider/enum-constant-contains-nested-properties.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkopropertyprovider/enum-constant-has-no-properties.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koenumconstant/snippet/forkopropertyprovider/enum-constant-has-two-properties.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kofile/KoFileDeclarationForKoDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kointerface/KoInterfaceDeclarationForKoDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koobject/KoObjectDeclarationForKoDeclarationProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoEnumConstantDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/DepracatedKoLocalClassProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/DeprecatedKoLocalDeclarationProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/DeprecatedKoLocalFunctionProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoEnumConstantDeclarationCore.kt
Labels: improvement

#1621 KON-701 Fix incorrect sourceDeclaration resolution for inner classes in parent declarations
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/KoParentDeclarationForKoSourceDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/class-with-parent-class-with-two-part-name-from-import.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/class-with-parent-class-with-two-part-name-from-the-same-file.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/class-with-parent-interface-with-two-part-name-from-import.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/class-with-parent-interface-with-two-part-name-from-the-same-file.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/interface-with-parent-interface-with-two-part-name-from-import.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/interface-with-parent-interface-with-two-part-name-from-the-same-file.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/object-with-parent-class-with-two-part-name-from-import.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/object-with-parent-class-with-two-part-name-from-the-same-file.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/object-with-parent-interface-with-two-part-name-from-import.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparent/snippet/forkosourcedeclarationprovider/object-with-parent-interface-with-two-part-name-from-the-same-file.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/testdata/TestData.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParentDeclarationCore.kt
Labels: bug-fix
