Repository LemonAppDev/konsist, pull requests merged in 2024-10, with the labels that each got.

#1404 KON-653 Deprecate `KoModifier.FUN`
  lib/src/main/kotlin/com/lemonappdev/konsist/api/KoModifier.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/modifierprovider/KoFunModifierProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/modifier/KoFunModifierProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoFunModifierProviderCore.kt
Labels: api-change

#1405 Update Java Version In Starter Projects
  samples/starter-projects/kmp-gradle-kotlin-junit5/build.gradle.kts
  samples/starter-projects/kmp-gradle-kotlin-kotest/build.gradle.kts
  samples/starter-projects/spring-gradle-kotlin-junit-5/build.gradle.kts
  samples/starter-projects/spring-gradle-kotlin-kotest/build.gradle.kts
Labels: documentation

#1406 Update README.md
  README.md
Labels: documentation

#1417 Add Serializable Snippet
  lib/src/snippet/kotlin/com/lemonappdev/konsist/AndroidSnippets.ktdoc
Labels: documentation

#1418 Fix Jobs that are failing forked repositories external
  .github/workflows/check-ktdoc-snippets.yml
  .github/workflows/check-kttest-snippets.yml
  .github/workflows/check-starter-projects.yml
Labels: maintenance

#1412 Optimize loading of KoFiles
  lib/src/main/kotlin/com/lemonappdev/konsist/core/container/KoScopeCreatorCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/util/KoFileDeclarationProvider.kt
Labels: improvement

#1430 Update Layer Documentation And Exception Messages
  lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/Layer.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/architecture/LayerTest.kt
Labels: documentation

#1431 Reorganize Konsist Tests
  lib/src/konsistTest/kotlin/com/lemonappdev/konsist/api/ApiKonsistTest.kt
  lib/src/konsistTest/kotlin/com/lemonappdev/konsist/api/KdocKonsistTest.kt
Labels: maintenance

#1440 Add Library Grant Program Winner Logo
  README.md
  misc/img.png
  misc/library-grant-program-winner.png
Labels: documentation

#1446 KON-661 Separate Declaration Name And Type In Errors
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/AssertTrueOnDeclarationListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/AssertTrueOnDeclarationSequenceTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/AssertTrueOnSingleDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/asserttrue/AssertTrueOnProviderListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/asserttrue/AssertTrueOnSingleProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt
Labels: improvement

#1392 KON-649 Add `sourceDeclaration` to `KoImportDeclaration` and `KoImportAliasDeclaration`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/KoImportDeclarationForKoSourceDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/snippet/forkosourcedeclarationprovider/class-source-declaration.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/snippet/forkosourcedeclarationprovider/external-source-declaration.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/snippet/forkosourcedeclarationprovider/function-source-declaration.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/snippet/forkosourcedeclarationprovider/interface-source-declaration.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/snippet/forkosourcedeclarationprovider/kotlin-source-declaration.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/snippet/forkosourcedeclarationprovider/object-source-declaration.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/snippet/forkosourcedeclarationprovider/property-source-declaration.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimport/snippet/forkosourcedeclarationprovider/typealias-source-declaration.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/KoImportAliasDeclarationForKoSourceDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/snippet/forkosourcedeclarationprovider/class-source-declaration.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/snippet/forkosourcedeclarationprovider/external-source-declaration.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/snippet/forkosourcedeclarationprovider/function-source-declaration.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/snippet/forkosourcedeclarationprovider/interface-source-declaration.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/snippet/forkosourcedeclarationprovider/kotlin-source-declaration.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/snippet/forkosourcedeclarationprovider/object-source-declaration.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/snippet/forkosourcedeclarationprovider/property-source-declaration.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koimportalias/snippet/forkosourcedeclarationprovider/typealias-source-declaration.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/KoGenericTypeDeclarationForKoGenericTypeProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/testdata/TestData.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoAnnotationDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoFunctionDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoImportAliasDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoImportDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoPropertyDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoSourceDeclarationProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoAnnotationDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFunctionDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoImportAliasDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoImportDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPropertyDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoSourceDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoBaseTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoKotlinTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoStarProjectionDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/model/DataCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoTypeDeclarationProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoTypeProviderCore.kt
Labels: improvement

#1449 KON-663 Add IsSortedByName And IsSortedBy Extensions
  lib/src/konsistTest/kotlin/com/lemonappdev/konsist/api/KdocKonsistTest.kt
  lib/src/konsistTest/kotlin/com/lemonappdev/konsist/core/DeclarationKonsistTest.kt
  lib/src/konsistTest/kotlin/com/lemonappdev/konsist/core/EnumKonsistTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/KoKDocTag.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/KoModifier.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/comparable/ComparableExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoNameProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/DependencyRulesCore.kt
  lib/src/snippet/kotlin/com/lemonappdev/konsist/GeneralSnippets.ktdoc
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoNameProviderListExtTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/comparable/ComparableExtTest.kt
Labels: improvement

#1451 KON-661 Separate Declaration Name And Type In Errors2
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/AssertTrueOnDeclarationListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/AssertTrueOnDeclarationSequenceTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/kodeclarationassert/asserttrue/AssertTrueOnSingleDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/asserttrue/AssertTrueOnProviderListTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/verify/koproviderassert/asserttrue/AssertTrueOnSingleProviderTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoDeclarationAndProviderAssertCore.kt
Labels: improvement

#1454 Update Docs
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoTypeArgumentProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/util/KoFileDeclarationProvider.kt
Labels: documentation

#1457 KON-666 Change comments "remove in 0.X.0 version" to Deprecated annotation
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFunctionDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoImportDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPropertyDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoSourceDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/combined/KoClassAndInterfaceAndObjectDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoTypeDeclarationProviderCore.kt
Labels: maintenance

#1458 KON-657 Deprecate isValModifier/isVarModifier and add isVal/isVar
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/KoParameterDeclarationForKoIsValProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/KoParameterDeclarationForKoIsVarProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/snippet/forkoisvalprovider/parameter-with-val-keyword.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/snippet/forkoisvalprovider/parameter-without-val-keyword.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/snippet/forkoisvarprovider/parameter-with-var-keyword.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koparameter/snippet/forkoisvarprovider/parameter-without-var-keyword.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationForKoIsValProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/KoPropertyDeclarationForKoIsVarProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoisvalprovider/property-defined-in-constructor-has-no-val-keyword.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoisvalprovider/property-defined-in-constructor-has-val-keyword.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoisvalprovider/property-has-no-val-keyword.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoisvalprovider/property-has-val-keyword.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoisvarprovider/property-defined-in-constructor-has-no-var-keyword.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoisvarprovider/property-defined-in-constructor-has-var-keyword.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoisvarprovider/property-has-no-var-keyword.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/koproperty/snippet/forkoisvarprovider/property-has-var-keyword.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kovariable/KoVariableDeclarationForKoIsValProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kovariable/KoVariableDeclarationForKoIsVarProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kovariable/snippet/forkoisvalprovider/variable-has-no-val-keyword.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kovariable/snippet/forkoisvalprovider/variable-has-val-keyword.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kovariable/snippet/forkoisvarprovider/variable-has-no-var-keyword.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/kovariable/snippet/forkoisvarprovider/variable-has-var-keyword.kttest
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoParameterDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoPropertyDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/KoVariableDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoIsValProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoIsVarProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/modifierprovider/KoValModifierProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/modifierprovider/KoVarModifierProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoIsValProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoIsVarProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/modifier/KoValModifierProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/modifier/KoVarModifierProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParameterDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPropertyDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoVariableDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoIsReadOnlyProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoIsValProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoIsVarProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoValModifierProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoVarModifierProviderCore.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoIsGenericTypeProviderListExtTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoIsValProviderListExtTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoIsVarProviderListExtTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoNullableProviderListExtTest.kt
Labels: improvement

#1460 Add Sponsor Information
  README.md
Labels: documentation

#1466 Add Spring Snippets
  lib/src/snippet/kotlin/com/lemonappdev/konsist/SpringSnippets.ktdoc
  lib/src/snippet/kotlin/dummyclasses/jakarta/transaction/annotation/Transactional.kt
  lib/src/snippet/kotlin/dummyclasses/org/springframework/security/access/prepost/PreAuthorize.kt
Labels: documentation

#1469 KON-671 Dont Allow Blank Arguments In Layer
  lib/src/main/kotlin/com/lemonappdev/konsist/api/architecture/Layer.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/architecture/LayerTest.kt
Labels: improvement

#1472 KON-672 Implement all properties inside core classes using lazy delegate
  lib/src/konsistTest/kotlin/com/lemonappdev/konsist/core/DeclarationKonsistTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoAnnotationDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoArgumentDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoClassDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoEnumConstantDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoExternalDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFileDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFunctionDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoGetterDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoImportAliasDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoImportDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoInitBlockDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoInterfaceDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoKDocDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoObjectDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPackageDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParameterDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPropertyDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoSetterDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoTypeAliasDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoTypeArgumentDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoVariableDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoDelegateProviderCore.kt
Labels: maintenance

#1482 Refactor Architecture Assertions
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/dependencyrules/DependencyRulesTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/architecture/DependencyRulesCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/verify/KoArchitectureAssert.kt
Labels: maintenance

#1484 Udpdate Architecture Test Descriptions
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture3/README.md
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture5/README.md
  lib/src/apiTest/kotlin/com/lemonappdev/konsist/architecture/assertarchitecture/architecture7/README.md
Labels: documentation

#1485 Update Readme
  README.md
  misc/library-grant-program-winner.png
Labels: documentation

#1490 KON-675 Add `Number` Type Basic Kotlin Types
  lib/src/main/kotlin/com/lemonappdev/konsist/core/util/TypeUtil.kt
Labels: bug-fix

#1497 KON-668 Change the version of deleting declarations annotated as deprecated in this release from 0.18.0 to 0.19.0
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/modifierprovider/KoValModifierProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/modifierprovider/KoVarModifierProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/modifier/KoValModifierProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/modifier/KoVarModifierProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/annotation/RemoveInVersion.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoFunctionDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoImportDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoParameterDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoPropertyDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoVariableDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/combined/KoClassAndInterfaceAndObjectDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoDeclarationCastProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoValModifierProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/modifier/KoVarModifierProviderCore.kt
  scripts/create_release.py
Labels: documentation
