Repository LemonAppDev/konsist, pull requests merged in 2024-09, with the labels that each got.

#1337 KON-632 Fix `.kttest` and `.ktdoc` github actions
  .github/workflows/check-ktdoc-snippets.yml
  .github/workflows/check-kttest-snippets.yml
  .github/workflows/check-starter-projects.yml
  scripts/check_kttest_snippets.py
Labels: maintenance

#1343 KON-633 Add final modifier to override methods
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/KoValuedKDocTagDeclarationCore.kt
Labels: maintenance

#1347 Update README.md
  README.md
Labels: documentation

#1353 KON-637 Types are not retrieved when placed on the same package
  detekt.yml
  lib/src/main/kotlin/com/lemonappdev/konsist/core/util/TypeUtil.kt
  test-projects/konsist-declaration-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/type/kotype/KoTypeForKoTypeDeclarationProviderTest.kt
  test-projects/konsist-declaration-tester/app/src/main/kotlin/com/lemonappdev/sample/fortypetest/ClassType.kt
  test-projects/konsist-declaration-tester/app/src/main/kotlin/com/lemonappdev/sample/fortypetest/DeclarationsWithParameter.kt
Labels: bug-fix

#1354 KON-638 Wrong type returned when using import alias
  lib/src/main/kotlin/com/lemonappdev/konsist/core/util/TypeUtil.kt
  test-projects/konsist-declaration-tester/app/src/integrationTest/kotlin/com/lemonappdev/konsist/declaration/type/kotype/KoTypeForKoTypeDeclarationProviderTest.kt
  test-projects/konsist-declaration-tester/app/src/main/kotlin/com/lemonappdev/sample/fortypetest/importaliascase/DeclarationsWithImportAliasType.kt
  test-projects/konsist-declaration-tester/app/src/main/kotlin/com/lemonappdev/sample/fortypetest/importaliascase/DeclarationsWithoutImportAliasType.kt
  test-projects/konsist-declaration-tester/app/src/main/kotlin/com/lemonappdev/sample/fortypetest/importaliascase/declarations/DeclarationTypeWithCorrectPackage.kt
  test-projects/konsist-declaration-tester/app/src/main/kotlin/com/lemonappdev/sample/fortypetest/importaliascase/declarations/DeclarationTypeWithOtherPackage.kt
  test-projects/konsist-declaration-tester/app/src/main/kotlin/com/lemonappdev/sample/fortypetest/packagecase/DeclarationType.kt
  test-projects/konsist-declaration-tester/app/src/main/kotlin/com/lemonappdev/sample/fortypetest/packagecase/DeclarationsWithParameter.kt
Labels: bug-fix

#1365 KON-641 Update script to create release
  scripts/create_release.py
Labels: maintenance

#1389 KON-646 Add extension functions for properties defined in `KoFunctionTypeDeclaration` and `KoGenericTypeDeclaration`
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/KoFunctionTypeDeclarationForKoFunctionTypeDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/KoFunctionTypeDeclarationTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/snippet/forkofunctiontypedeclarationprovider/parameters-list-has-one-element.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/snippet/forkofunctiontypedeclarationprovider/parameters-list-has-two-elements.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/snippet/forkofunctiontypedeclarationprovider/parameters-list-is-empty.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/snippet/forkofunctiontypedeclarationprovider/return-type-is-collection-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/snippet/forkofunctiontypedeclarationprovider/return-type-is-complex-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kofunctiontype/snippet/forkofunctiontypedeclarationprovider/return-type-is-kotlin-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/KoGenericTypeDeclarationForKoGenericTypeDeclarationProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/class-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/class-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/external-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/external-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/few-type-arguments.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/function-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/generic-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/import-alias-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/import-alias-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/interface-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/interface-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/kotlin-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/kotlin-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/nested-generic-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/nested-generic-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/object-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kogenerictype/snippet/forkogenerictypedeclarationprovider/typealias-type-argument.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/KoTypeDeclarationForKoTypeDeclarationProviderTest.kt
  lib/src/konsistTest/kotlin/com/lemonappdev/konsist/api/ApiKonsistTest.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/type/KoFunctionTypeDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/type/KoGenericTypeDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoFunctionTypeDeclarationProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoGenericTypeDeclarationProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoTypeDeclarationProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoTypeProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoFunctionTypeDeclarationProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoGenericTypeDeclarationProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoTypeDeclarationProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoFunctionTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoGenericTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoFunctionTypeDeclarationProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoGenericTypeDeclarationProviderCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoTypeDeclarationProviderCore.kt
  lib/src/snippet/kotlin/com/lemonappdev/konsist/GenericTypesSnippets.ktdoc
  lib/src/snippet/kotlin/com/lemonappdev/konsist/GenericTypesSnippets.md
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoFunctionTypeDeclarationProviderListExtTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoGenericTypeDeclarationProviderListExtTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoTypeDeclarationProviderListExtTest.kt
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoTypeProviderListExtTest.kt
Labels: improvement

#1391 KON-636 Add `isMutableType`
  lib/libs/sample-external-library-1.2.jar
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/KoTypeDeclarationForKoIsMutableTypeProviderTest.kt
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/class-type-is-mutable-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/class-type-is-not-mutable-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/external-type-is-mutable-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/external-type-is-not-mutable-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/function-type-type-is-not-mutable-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/generic-type-is-mutable-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/generic-type-is-not-mutable-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/import-alias-type-is-mutable-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/import-alias-type-is-not-mutable-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/interface-type-is-mutable-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/interface-type-is-not-mutable-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/kotlin-type-is-mutable-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/kotlin-type-is-not-mutable-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/object-type-is-mutable-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/object-type-is-not-mutable-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/typealias-type-is-mutable-type.kttest
  lib/src/integrationTest/kotlin/com/lemonappdev/konsist/core/declaration/type/kotype/snippet/forkoismutabletypeprovider/typealias-type-is-not-mutable-type.kttest
  lib/src/main/kotlin/com/lemonappdev/konsist/api/declaration/type/KoTypeDeclaration.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/ext/list/KoIsMutableTypeProviderListExt.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/api/provider/KoIsMutableTypeProvider.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/declaration/type/KoTypeDeclarationCore.kt
  lib/src/main/kotlin/com/lemonappdev/konsist/core/provider/KoIsMutableTypeProviderCore.kt
  lib/src/snippet/kotlin/com/lemonappdev/konsist/GeneralSnippets.ktdoc
  lib/src/test/kotlin/com/lemonappdev/konsist/api/ext/list/KoIsMutableTypeProviderListExtTest.kt
  projects/helper-projects/README.md
  projects/helper-projects/sample-external-library.zip
Labels: improvement

#1395 KON-376 Update Dokka Task Name
  .github/workflows/check.yml
  .github/workflows/publish-dokka.yml
  buildSrc/src/main/kotlin/local.dokka.gradle.kts
Labels: maintenance
